spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${}:${}/${}
    username: postgres
    password: ${}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate